### ISSUE TITLE
Crash on Loading in

### ISSUE THREAD

**Issue by Eclipsum** [Speshkitty/DalamudPlugins#1]
Helper crashes whenever i enter a new instance,load in from the login screen or teleport anywhere disabling the plugin fixes it.
and i would like to know if its only on my side.

**Comment by Speshkitty** [comment]
I suspect it's due to a lack of error handling on my part and some internet issues yesterday - I plan to overhaul the plugin & backend soon, but in the meantime it should be working again.

**Comment by Mashbraganca** [comment]
It is still happening for me, oh well, I will wait for the overhaul, thanks for the hard work
